### ISSUE TITLE
electron-prebuilt name is deprecated

### ISSUE THREAD

**Issue by ghost** [IonicaBizau/electroner#8]
According to the repo description for electron-prebuilt, the name `electron-prebuilt` is deprecated and will eventually be replaced with `electron`. Do you want to change the argument to the require function to reflect that?

**Comment by IonicaBizau** [comment]
Definitely. Contributions are welcome!

**Comment by ghost** [comment]
Sure, I'll submit a pull request then.

**Comment by IonicaBizau** [comment]
Fixed via #9.
